services:
  pop:
    build: .
    ports:
      - "8011:8011"
    env_file:
      - path: .env
        required: false
    environment:
      HOSTNAME: 0.0.0.0
      PORT: 8011
      POP_DATABASE_PATH: /app/data/replays.sqlite3
    volumes:
      - ./data:/app/data
    restart: unless-stopped
